import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col bg-zinc-950 text-zinc-100">
        <main className="flex-1 flex flex-col">{children}</main>
        <footer className="w-full py-3.5 text-center text-xs text-zinc-100 border-t border-zinc-800 bg-zinc-900/90 select-none">
          Developed by <span className="text-amber-400 font-semibold tracking-wider">Rohit</span>
        </footer>
      </body>
    </html>
  );
}
